import React, {useEffect, useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';

const names = {pending:'Pending', processing:'Processing', sending:'Sending', sent:'Sent', retry:'Retry'};
const errors = {login_required:'Please sign in.', incorrect_password:'Incorrect password.', login_rate_limited:'Too many attempts. Try again in 5 minutes.', setup_dashboard_password_in_terminal:'Run python dashboard.py setup first.', verify_telegram_first:'Verify Telegram in the terminal first.', verify_gmail_first:'Verify Gmail in the terminal first.', missing_or_invalid_model:'Configure the API key in the terminal first.', demo_read_only:'Read-only demo.', invalid_model_endpoint:'Enter a valid HTTPS endpoint without credentials.', model_and_prompt_required:'Model and prompt are required.', settings_conflict_refresh:'Settings changed. Reload and try again.', configuration_changed_retry:'Configuration changed. Test again.'};
async function api(path, body) {
  const response = await fetch('/api'+path, {method:body===undefined?'GET':'POST', credentials:'same-origin', headers:body===undefined?{}:{'Content-Type':'application/json','X-Requested-With':'MailConsole'}, body:body===undefined?undefined:JSON.stringify(body)});
  const value = await response.json();
  if (!response.ok) {
    if(response.status===401 && path!=='/login') window.dispatchEvent(new Event('session-expired'));
    throw new Error(errors[value.error] || value.error || 'Request failed.');
  }
  return value;
}
const date = value => value ? new Date(value*1000).toLocaleString('en-GB',{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}) : '—';
const seconds = value => value==null ? '—' : value+' s';
function Icon({name, size=20}) {
  const paths = {grid:<><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></>,mail:<><rect x="3" y="5" width="18" height="14" rx="3"/><path d="m3 7 9 6 9-6"/></>,prompt:<><path d="M7 4h10M12 4v16M8 20h8M4 8V4h16v4"/></>,model:<><path d="m12 2 9 5v10l-9 5-9-5V7Z"/><path d="m3 7 9 5 9-5M12 12v10M7 4l10 6"/></>,logs:<><path d="M7 3h10a2 2 0 0 1 2 2v16l-4-2-3 2-3-2-4 2V5a2 2 0 0 1 2-2Z"/><path d="M9 8h6M9 12h6"/></>,arrow:<><path d="M5 12h14m-5-5 5 5-5 5"/></>,refresh:<><path d="M20 7v5h-5M4 17v-5h5"/><path d="M6 7a7 7 0 0 1 12-2l2 3M4 16l2 3a7 7 0 0 0 12-2"/></>,check:<path d="m5 12 4 4L19 6"/>,search:<><circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/></>,clock:<><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></>,send:<><path d="m21 3-7 18-4-7-7-4Z"/><path d="m10 14 5-5"/></>,lock:<><rect x="5" y="10" width="14" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3"/></>,exit:<><path d="M10 4H4v16h6M14 8l4 4-4 4M8 12h12"/></>};
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.65" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{paths[name] || paths.grid}</svg>;
}

function Status({state}) { return <span className={'badge '+state}><i/>{names[state]||state}</span>; }
function Empty({title='No records'}) { return <div className="empty">{title}</div>; }
function Pager({data,onChange}) { return data && data.total>data.limit ? <div className="pager"><span>{data.total} records · Page {data.page+1}</span><div><button className="button small" disabled={!data.page} onClick={()=>onChange(data.page-1)}>Previous</button><button className="button small" disabled={(data.page+1)*data.limit>=data.total} onClick={()=>onChange(data.page+1)}>Next</button></div></div> : null; }
function MailTable({data,select,compact=false}) {
  if(!data) return <Empty title="Loading…"/>;
  if(!data.items.length) return <Empty/>;
  return <div className="table-scroll"><table><thead><tr><th>Email</th><th>Status</th><th>Latency</th><th>Received</th><th aria-label="Details"/></tr></thead><tbody>{data.items.slice(0,compact?5:20).map(row=><tr key={row.id}><td><button className="mail-title" onClick={()=>select(row)}>{row.subject||'Email #'+row.id}</button><span className="sender">{row.sender||'—'}</span></td><td><Status state={row.state}/></td><td className={row.latency>60?'warning-text':'mono'}>{seconds(row.latency)}</td><td className="muted nowrap">{date(row.received)}</td><td><button className="icon-button" onClick={()=>select(row)} aria-label={'View '+(row.subject||row.id)}><Icon name="arrow" size={16}/></button></td></tr>)}</tbody></table></div>;
}
function Overview({data,mail,select,navigate}) {
  const online=data?.heartbeat.worker_ok!=null && data.heartbeat.worker_ok<120;
  const metrics=[['Sent · 24h',data?.sent_24h??'—'],['Avg. latency · 24h',seconds(data?.average_seconds)],['Under 60s · 24h',data?.on_time_percent==null?'—':data.on_time_percent+'%'],['Pending / retry',data?(data.counts.pending||0)+(data.counts.retry||0):'—']];
  return <><div className="intro"><h1>Overview</h1><span className={'service-state '+(online?'online':'')}><i/>{data?(online?'Running':'Offline'):'Loading…'}</span></div><div className="metrics">{metrics.map(([label,value])=><div className="metric" key={label}><div className="metric-label">{label}</div><strong>{value}</strong></div>)}</div><div className="connections">{['gmail','model','telegram'].map(key=><div key={key}><strong>{key==='gmail'?'Gmail':key==='model'?'Model':'Telegram'}</strong><span>{data?.connections[key]?.verified?'Verified':data?.connections[key]?.configured?'Unverified':'Not configured'}</span></div>)}</div><section className="panel"><div className="panel-heading"><h2>Recent emails</h2><button className="text-button" onClick={()=>navigate('inbox')}>View all <Icon name="arrow" size={16}/></button></div><MailTable data={mail} select={select} compact/></section></>;
}
function SettingsEditor({kind,settings,setSettings,draft,setDraft,demo,notify}) {
  const [busy,setBusy]=useState(false),[result,setResult]=useState(null);
  const dirty=JSON.stringify(draft)!==JSON.stringify(settings.draft);
  const change=(key,value)=>setDraft(old=>({...old,[key]:value}));
  async function save(){setBusy(true);try{const next=await api('/settings',{draft,revision:settings.revision});setSettings(next);setDraft(next.draft);setResult(null);notify('Draft saved.')}catch(e){notify(e.message,true)}finally{setBusy(false)}}
  async function activate(){setBusy(true);try{const next=await api('/activate',{revision:settings.revision});setSettings(next.settings);setResult(next);notify('Test passed. Settings active.')}catch(e){notify(e.message,true)}finally{setBusy(false)}}
  return <><div className="intro"><h1>{kind==='prompt'?'Prompt':'Model / API'}</h1><span className="muted">{dirty?'Unsaved changes':'Draft saved'}</span></div><section className="panel editor compact-editor">
    {kind==='prompt'?<><label htmlFor="prompt">Summary prompt</label><textarea id="prompt" className="prompt-area" maxLength={5000} value={draft.prompt} onChange={e=>change('prompt',e.target.value)} spellCheck="false"/><div className="field-foot"><span>Summary language: English</span><span>{draft.prompt.length} / 5000</span></div></>:<>
      <label htmlFor="model">Model</label><input id="model" list="model-list" value={draft.model} onChange={e=>change('model',e.target.value)} placeholder="Model ID" autoComplete="off"/><datalist id="model-list">{draft.model_options.filter(Boolean).map(v=><option key={v} value={v}/>)}</datalist>
      <label htmlFor="endpoint">API endpoint</label><input id="endpoint" type="url" value={draft.endpoint} onChange={e=>change('endpoint',e.target.value)} placeholder="https://api.example.com/v1/chat/completions" spellCheck="false"/>
      <label htmlFor="model-options">Saved models · one per line</label><textarea id="model-options" rows={3} value={draft.model_options.join('\n')} onChange={e=>change('model_options',e.target.value.split('\n'))} onBlur={()=>change('model_options',[...new Set(draft.model_options.map(v=>v.trim()).filter(Boolean))])} placeholder={'model-a\nmodel-b'}/>
      <div className="key-state"><Icon name="lock" size={17}/><div><strong>API key: {settings.api_key_configured?'Configured':'Not configured'}</strong><p>Update in terminal: <code>python mailagent.py setup-model</code></p></div></div>
    </>}
    <div className="editor-actions"><span>{demo?'Read-only demo':busy?'Testing…':'Test uses the configured API.'}</span><button className="button" disabled={busy||demo||!dirty} onClick={save}>Save draft</button><button className="button primary" disabled={busy||demo||dirty} onClick={activate}>{busy?'Testing…':'Test & apply'}</button></div>
    {result&&<div className="test-result"><code>{result.trace.join(' → ')}</code><p>{result.summary}</p></div>}
    <details className="active-settings"><summary>Active settings</summary><dl><dt>Model</dt><dd>{settings.active.model||'—'}</dd><dt>Endpoint</dt><dd>{settings.active.endpoint||'—'}</dd><dt>Applied</dt><dd>{date(settings.activated_at)}</dd></dl><pre>{settings.active.prompt}</pre></details>
  </section></>;
}
function App(){
  const [session,setSession]=useState(null),[page,setPage]=useState('overview'),[password,setPassword]=useState(''),[loginBusy,setLoginBusy]=useState(false);
  const [overview,setOverview]=useState(null),[mail,setMail]=useState(null),[logs,setLogs]=useState(null),[settings,setSettings]=useState(null),[draft,setDraft]=useState(null);
  const [query,setQuery]=useState(''),[state,setState]=useState(''),[mailPage,setMailPage]=useState(0),[logPage,setLogPage]=useState(0),[onlyErrors,setOnlyErrors]=useState(false);
  const [selected,setSelected]=useState(null),[toast,setToast]=useState(null),[updated,setUpdated]=useState(null),[refreshing,setRefreshing]=useState(false);
  const notify=(message,error=false)=>setToast({message,error});
  useEffect(()=>{api('/session').then(setSession).catch(e=>notify(e.message,true));const expired=()=>{setSession(s=>({...s,authenticated:false}));setSelected(null);setMail(null);setLogs(null);setOverview(null);setSettings(null);setDraft(null)};window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired)},[]);
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(null),6000);return()=>clearTimeout(timer)},[toast]);
  useEffect(()=>{if(!selected)return;const close=e=>{if(e.key==='Escape')setSelected(null)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[selected]);
  useEffect(()=>{if(!draft||!settings||JSON.stringify(draft)===JSON.stringify(settings.draft))return;const guard=e=>{e.preventDefault();e.returnValue=''};window.addEventListener('beforeunload',guard);return()=>window.removeEventListener('beforeunload',guard)},[draft,settings]);
  const fetchData=()=>Promise.all([api('/overview'),api('/mail?'+new URLSearchParams({page:mailPage,state,q:query})),api('/logs?'+new URLSearchParams({page:logPage,errors:onlyErrors?'1':'0'}))]);
  const showData=data=>{setOverview(data[0]);setMail(data[1]);setLogs(data[2]);setUpdated(Date.now())};
  async function refresh(){setRefreshing(true);try{showData(await fetchData())}catch(e){notify(e.message,true)}finally{setRefreshing(false)}}
  useEffect(()=>{if(!session?.authenticated)return;let cancelled=false;const load=async()=>{try{const data=await fetchData();if(!cancelled)showData(data)}catch(e){if(!cancelled)notify(e.message,true)}};const debounce=setTimeout(load,200);const interval=setInterval(()=>{if(!document.hidden)load()},10000);return()=>{cancelled=true;clearTimeout(debounce);clearInterval(interval)}},[session?.authenticated,mailPage,state,query,logPage,onlyErrors]);
  useEffect(()=>{if(session?.authenticated)api('/settings').then(value=>{setSettings(value);setDraft(value.draft)}).catch(e=>notify(e.message,true))},[session?.authenticated]);
  async function login(e){e.preventDefault();setLoginBusy(true);try{await api('/login',{password});setPassword('');setSession(await api('/session'))}catch(e){notify(e.message,true)}finally{setLoginBusy(false)}}
  async function logout(){try{await api('/logout',{});window.dispatchEvent(new Event('session-expired'))}catch(e){notify(e.message,true)}}
  const nav=[['overview','grid','Overview'],['inbox','mail','Emails'],['prompt','prompt','Prompt'],['model','model','Model / API'],['logs','logs','Logs']];
  const notification=toast&&<div role="alert" className={'toast '+(toast.error?'error':'')}>{toast.message}</div>;
  if(!session?.authenticated)return <main className="simple-login"><form onSubmit={login}><span className="login-logo"><Icon name="mail" size={25}/></span><h1>Mail Agent</h1><label htmlFor="password">Password</label><input id="password" type="password" autoComplete="current-password" value={password} onChange={e=>setPassword(e.target.value)} required/><button className="button primary" disabled={loginBusy||!session}>{loginBusy?'Signing in…':'Sign in'}</button>{session&&!session.configured&&<p className="field-help">First run: <code>python dashboard.py setup</code></p>}</form>{notification}</main>;
  return <div className="app-shell"><aside className="sidebar"><a className="brand" href="#" onClick={e=>{e.preventDefault();setPage('overview')}}><span className="brand-mark"><Icon name="mail" size={22}/></span><span>Mail Agent</span></a><nav aria-label="Main navigation">{nav.map(([id,icon,label])=><button key={id} aria-label={label} className={page===id?'active':''} onClick={()=>setPage(id)}><Icon name={icon}/>{label}</button>)}</nav><div className="sidebar-foot"><span>Tommy</span><button className="icon-button" aria-label="Sign out" onClick={logout} disabled={session.demo}><Icon name="exit" size={18}/></button></div></aside><div className="workspace"><header className="topbar"><span>{nav.find(x=>x[0]===page)[2]}</span><div className="topbar-right"><span className="refresh-time">{updated?'Updated '+new Date(updated).toLocaleTimeString('en-GB'):'Connecting…'}</span><button className={'icon-button '+(refreshing?'spinning':'')} onClick={refresh} disabled={refreshing} aria-label="Refresh"><Icon name="refresh" size={17}/></button></div></header>{session.demo&&<div className="demo-banner">Demo · Sample data · Read only</div>}<main className="main-content">
    {page==='overview'&&<Overview data={overview} mail={mail} select={setSelected} navigate={setPage}/>}
    {page==='inbox'&&<><div className="intro"><h1>Emails</h1><span className="muted">{mail?.total??0} records</span></div><section className="panel"><div className="table-toolbar"><div className="search"><Icon name="search" size={17}/><input aria-label="Search emails" value={query} onChange={e=>{setQuery(e.target.value);setMailPage(0)}} placeholder="Search emails"/></div><select aria-label="Filter status" value={state} onChange={e=>{setState(e.target.value);setMailPage(0)}}><option value="">All statuses</option>{Object.entries(names).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div><MailTable data={mail} select={setSelected}/><Pager data={mail} onChange={setMailPage}/></section></>}
    {(page==='prompt'||page==='model')&&(settings&&draft?<SettingsEditor kind={page} settings={settings} setSettings={setSettings} draft={draft} setDraft={setDraft} demo={session.demo} notify={notify}/>:<Empty title="Loading…"/>)}
    {page==='logs'&&<><div className="intro"><h1>Logs</h1><span className="muted">Last 30 days</span></div><section className="panel"><div className="panel-heading"><h2>Events</h2><label className="checkbox"><input type="checkbox" checked={onlyErrors} onChange={e=>{setOnlyErrors(e.target.checked);setLogPage(0)}}/>Errors only</label></div>{logs?.items.length?<div className="event-list">{logs.items.map(row=><div className="event-row" key={row.seq}><span className={'event-dot '+(['retry','collector_retry','model_test_failed'].includes(row.kind)?'warn':'')}/><span className="event-time mono">{date(row.at)}</span><div><strong>{row.kind}</strong>{(row.code||row.attempt)&&<span>{row.code||''}{row.attempt?' · Attempt '+row.attempt:''}</span>}</div><code>{row.job_id?'#'+row.job_id:'SYSTEM'}</code></div>)}</div>:<Empty title={logs?'No events':'Loading…'}/>}<Pager data={logs} onChange={setLogPage}/></section></>}
    </main></div>{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="detail-panel" role="dialog" aria-modal="true" aria-labelledby="detail-title" onClick={e=>e.stopPropagation()}><div className="panel-heading"><h3>Email details</h3><button className="button small" autoFocus onClick={()=>setSelected(null)}>Close</button></div><Status state={selected.state}/><h2 id="detail-title">{selected.subject||'Email #'+selected.id}</h2><p className="muted break">{selected.sender||'—'}</p><dl className="detail-grid"><div><dt>Email ID</dt><dd>{selected.id}</dd></div><div><dt>Received</dt><dd>{date(selected.received)}</dd></div><div><dt>Latency</dt><dd>{seconds(selected.latency)}</dd></div><div><dt>Attempts</dt><dd>{selected.attempts}</dd></div><div><dt>Telegram ID</dt><dd>{selected.telegram_id??'—'}</dd></div><div><dt>Next retry</dt><dd>{selected.state==='retry'?date(selected.next_try):'—'}</dd></div></dl><h3>Summary</h3><div className="summary-text">{selected.summary||'No summary available.'}</div>{selected.last_error&&<div className="error-note">{selected.last_error}</div>}</section></div>}{notification}</div>;
}
createRoot(document.getElementById('root')).render(<App/>);
